export const ROUTES = {
  ROOT: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  ONBOARDING: '/onboarding',
  ORG_ROOT: '/:organizationId',
  ORG_SETTINGS: '/:organizationId/settings',
  ORG_SETTINGS_SECTION: '/:organizationId/settings/:section',
  ORG_INTEGRATIONS: '/:organizationId/integrations',
  ORG_INTEGRATION: '/:organizationId/integrations/:integration',
  PROJECT_CREATE: '/:organizationId/projects/new',
  PROJECT_ROOT: '/:organizationId/:projectId',
  PROJECT_RELEASES: '/:organizationId/:projectId/releases',
  PROJECT_RELEASE_BUILDER: '/:organizationId/:projectId/releases/new',
  PROJECT_RELEASE_DETAIL: '/:organizationId/:projectId/releases/:releaseId',
  PROJECT_FEATURES: '/:organizationId/:projectId/features',
  PROJECT_FEATURE_DETAIL: '/:organizationId/:projectId/features/:id',
  PROJECT_FLAGS: '/:organizationId/:projectId/flags',
  PROJECT_FLAG_DETAIL: '/:organizationId/:projectId/flags/:flagKey',
  PROJECT_REPO_OPS: '/:organizationId/:projectId/repo-ops',
  PROJECT_SETTINGS: '/:organizationId/:projectId/settings',
  PROJECT_SETTINGS_SECTION: '/:organizationId/:projectId/settings/:section',
  INVITE: '/invite/:token',
  GITHUB_SETUP: '/github/setup',
} as const
